language: generic

sudo: required

services:
  - docker

# before_install:
#   - docker build -t toeydocker/react-test:v1 -f ./app/Dockerfile.dev .

# script:
#   - ls
#   - ls ./app
#   - docker run -e CI=true toeydocker/react-test:v1 npm run test 

after_success:
  - docker build -t toeydocker/multi-docker-server:v1 ./api
  - docker build -t toeydocker/multi-docker-worker:v1 ./worker
  - docker build -t toeydocker/multi-docker-nginx:v1 ./nginx
  - docker build -t toeydocker/multi-docker-react:v1 ./app
  #  LOGIN TO DOCKER REGISTRY
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toeydocker/multi-docker-server:v1
  - docker push toeydocker/multi-docker-worker:v1
  - docker push toeydocker/multi-docker-nginx:v1
  - docker push toeydocker/multi-docker-react:v1

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "DockerReact-env"
  bucket_name: "eelasticbeanstalk-us-east-2-781381994409/"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY