language: generic

sudo: required

services:
  - docker

# before_install:
#   - docker build -t toeydocker/react-test:v1 -f ./app/Dockerfile.dev .

script:
  - echo $ACK
  - ls ./app
  - docker run -e CI=true toeydocker/react-test:v1 npm run test 

after_success:
  - docker build -t toeydocker/multi-docker-server:v1 ./api
  - docker build -t toeydocker/multi-docker-worker:v1 ./worker
  - docker build -t toeydocker/multi-docker-nginx:v1 ./nginx
  - docker build -t toeydocker/multi-docker-react:v1 ./app
  #  LOGIN TO DOCKER REGISTRY
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toeydocker/multi-docker-server:v1
  - docker push toeydocker/multi-docker-worker:v1
  - docker push toeydocker/multi-docker-nginx:v1
  - docker push toeydocker/multi-docker-react:v1

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mu;ti-docker3"
  env: "MutiDocker3-env"
  bucket_name: "elasticbeanstalk-us-east-2-781381994409"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY