language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t toeydocker/react-test:v1 -f ./app/Dockerfile.dev .

script:
  - docker run -e CI=true toeydocker/multi-docker-react:v1 npm run test 

after_success:
  - docker build -t toeydocker/multi-docker-server:v1 -f ./server
  - docker build -t toeydocker/multi-docker-worker:v1 -f ./worker
  - docker build -t toeydocker/multi-docker-nginx:v1 -f ./nginx
  - docker build -t toeydocker/multi-docker-react:v1 -f ./app
  #  LOGIN TO DOCKER REGISTRY
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toeydocker/multi-docker-server:v1
  - docker push toeydocker/multi-docker-worker:v1
  - docker push toeydocker/multi-docker-nginx:v1
  - docker push toeydocker/multi-docker-react:v1

